DROP TABLE IF EXISTS user;
CREATE TABLE users (
    userId INT AUTO_INCREMENT  PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    sirname VARCHAR(50) NOT NULL,
    phonenumber VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    adress VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL
);
